Us53 coureur
WildCodeSchool/orleans-0219-php-gtb pull request #113
Opened 2019-07-01 14:56 UTC by laheravilla

2019-07-01 15:12 UTC, lamoureux-sylvain approved these changes

2019-07-01 15:49 UTC, sblondeau requested changes

2019-07-01 15:49 UTC, sblondeau commented on templates/member/index.html.twig
> +        <li>Your controller at <code><a href="{{ '/home/yurniel/Projects/orleans-0219-php-gtb/src/Controller/MemberController.php'|file_link(0) }}">src/Controller/MemberController.php</a></code></li>
ce fichier est à supprimer si tu ne t'en sers pas, regards tu as des infos perso dedans (path vers ton directory)

2019-07-01 15:49 UTC, sblondeau commented on src/Controller/MemberController.php
> +    public function index()
méthode à enlever si tu ne t'en sers pas

2019-07-02 06:21 UTC, lamoureux-sylvain approved these changes

2019-07-02 06:48 UTC, laheravilla commented on src/Controller/MemberController.php
> +    public function index()
done

2019-07-02 06:48 UTC, laheravilla commented on templates/member/index.html.twig
> +        <li>Your controller at <code><a href="{{ '/home/yurniel/Projects/orleans-0219-php-gtb/src/Controller/MemberController.php'|file_link(0) }}">src/Controller/MemberController.php</a></code></li>
done

2019-07-02 07:02 UTC, sblondeau approved these changes

2019-07-02 07:02 UTC, merged