Fix membercreate
WildCodeSchool/orleans-0219-php-gtb pull request #134
Opened 2019-07-03 14:19 UTC by MaistrePedro

2019-07-03 14:24 UTC, vangjeannette approved these changes

2019-07-03 20:56 UTC, sblondeau requested changes

2019-07-03 20:56 UTC, sblondeau commented on src/Controller/UserController.php
> +            'users' => $userRepository->findBy([], ['roles' => 'ASC']),
tu veux trier par role ? par exemple les admins en premier ? 
ça me va sur le principe, mais ajouter également un tri par nom/prénom aussi !
             'users' => $userRepository->findBy([], ['roles' => 'ASC', 'lastname'=>'ASC', 'firstname'=>'ASC']),

2019-07-03 20:56 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Length(min="2", max="255", minMessage="votre prénom doit comporter au minimum {{ limit }} caractères" ,
pas de taille min pour les noms ou prénoms stp
par exemple 'Y' es u nom de famille qui existe. Dommage de bloquer pour ça, le NotBlank évite déjà les tailles à 0, tu exclus donc toutes les personnes ayant un nom ou prénom pourquoi pas, à un seul caractère

2019-07-04 06:32 UTC, MaistrePedro commented on src/Entity/User.php
> +     * @Assert\Length(min="2", max="255", minMessage="votre prénom doit comporter au minimum {{ limit }} caractères" ,
Résolu !

2019-07-04 06:33 UTC, MaistrePedro commented on src/Controller/UserController.php
> +            'users' => $userRepository->findBy([], ['roles' => 'ASC']),
Résolu !

2019-07-04 07:38 UTC, sblondeau approved these changes

2019-07-04 07:39 UTC, merged