Admin showing all gallery images
WildCodeSchool/orleans-0219-php-gtb pull request #135
Opened 2019-07-03 14:38 UTC by laheravilla

2019-07-03 14:47 UTC, lamoureux-sylvain approved these changes

2019-07-03 21:00 UTC, sblondeau requested changes

2019-07-03 21:00 UTC, sblondeau commented on templates/admin/galery.html.twig
> +    <script src="node_modules/summernote/src/js/summernote.js"></script>
summernote est inutile sur cette page non ?

2019-07-03 21:00 UTC, sblondeau commented on src/Controller/GaleryController.php
> +    public function showAll(GaleryRepository $galeryRepository): Response
généralement par commodité, tout ce qui concerne l'admin est dans un autre controller (par ex AdminGaleryController), c'est souvent plus simple ensuite pour protéger les routes de manière global sur toutes les méthodes d'un controller

2019-07-03 21:00 UTC, sblondeau commented on templates/admin/galery.html.twig
> +                        <span class="position-absolute"><a href="#" class="js-delete-sponsor" data-url=""><i class="fas fa-trash-alt"></i></a></span>
tu à un data-url vide, ça sert à qq chose ?

2019-07-04 03:27 UTC, laheravilla commented on templates/admin/galery.html.twig
> +                        <span class="position-absolute"><a href="#" class="js-delete-sponsor" data-url=""><i class="fas fa-trash-alt"></i></a></span>
Oui, je prepare la suppression d'une photo avec ajax comme pour les partenaires

2019-07-04 03:27 UTC, laheravilla commented on templates/admin/galery.html.twig
> +    <script src="node_modules/summernote/src/js/summernote.js"></script>
Done

2019-07-04 03:45 UTC, laheravilla commented on src/Controller/GaleryController.php
> +    public function showAll(GaleryRepository $galeryRepository): Response
Done

2019-07-04 06:50 UTC, MaistrePedro approved these changes

2019-07-04 07:39 UTC, sblondeau approved these changes

2019-07-04 07:39 UTC, merged