Sprint 05 crud commentaires
WildCodeSchool/orleans-0219-php-gtb pull request #136
Opened 2019-07-03 14:57 UTC by lamoureux-sylvain

https://drive.google.com/open?id=1ePwqyzZBkk8a3Z9MQZlTPziT9DCGpuDaJLfT78M2eYU

2019-07-03 15:03 UTC, laheravilla approved these changes

2019-07-03 21:04 UTC, sblondeau requested changes

2019-07-03 21:04 UTC, sblondeau commented on templates/comment/show.html.twig
> +                <td>{{ comment.user.firstname }}</td>
il ne faudrati mieux pas aussi concaténer le lastname au firstname ?

2019-07-03 21:04 UTC, sblondeau commented on templates/comment/show.html.twig
> +            <a class="btn" href="{{ path('comment_index') }}">retour à la liste</a>
normalement on ne mets pas "que" btn. C'est btn btn-primary par ex, voire btn btn-link de mémoire

2019-07-04 07:37 UTC, vangjeannette approved these changes

2019-07-04 07:43 UTC, sblondeau requested changes
la US n'est pas très claire. C'est un show, un edit, un add, une modération ?
au delà de ça, il me manque les Assert sur l'entity Comment

2019-07-04 07:43 UTC, sblondeau commented on src/Entity/Comment.php
> +     * @ORM\Column(type="boolean", nullable=false)
manque les assert
y un @assert\Type ou tu dois pouvoir préciser boolean si je ne dis pas de bétise
il faut aussi un assert DateTime pour la date et ça devrait etre bon

2019-07-04 07:49 UTC, lamoureux-sylvain commented on src/Entity/Comment.php
> +     * @ORM\Column(type="boolean", nullable=false)
je changes ça et je te renvoi la PR ASAP

2019-07-04 07:56 UTC, lamoureux-sylvain commented
l'us ici traite de la modération des commentaires, pour l'ajout des commentaires aux events Yurniel attends la validation de cette PR.

Le but est d'avoir une visibilité sur les commentaires laissés et de pouvoir au besoin les mettres hors ligne voir de les supprimer.

2019-07-04 07:56 UTC, vangjeannette approved these changes

2019-07-04 08:00 UTC, sblondeau approved these changes

2019-07-04 08:08 UTC, vangjeannette approved these changes

2019-07-04 08:08 UTC, MaistrePedro approved these changes

2019-07-04 08:13 UTC, merged