Sprint05 us67 approbation comptes
WildCodeSchool/orleans-0219-php-gtb pull request #142
Opened 2019-07-04 15:46 UTC by MaistrePedro

On a besoin que cette PR passe pour la gestion des rôles que Sylvain est en train de faire

2019-07-04 19:25 UTC, vangjeannette approved these changes

2019-07-04 21:01 UTC, sblondeau requested changes

2019-07-04 21:01 UTC, sblondeau commented on src/Entity/User.php
> +    public function getRoleChoices(): array
te sert à quoi cette méthode ?
d'autant que tu ne fais que retourne self::ROLES au final.

2019-07-04 21:01 UTC, sblondeau commented on src/Entity/User.php
> +        $roles[0] = 'ROLE_USER';
pourquoi le 0 en dur ?

2019-07-05 06:32 UTC, MaistrePedro commented on src/Entity/User.php
> +        $roles[0] = 'ROLE_USER';
Parce que je veux écraser le rôle à chaque fois, c'est ce dont je te parlais, je veux pouvoir l'écraser dans le cas d'une révocation de droits

2019-07-05 06:33 UTC, MaistrePedro commented on src/Entity/User.php
> +    public function getRoleChoices(): array
C'est pour l'édition au niveau admin

2019-07-08 13:40 UTC, closed without merging