Sprint05 us78925 trombi
WildCodeSchool/orleans-0219-php-gtb pull request #150
Opened 2019-07-05 11:41 UTC by MaistrePedro

2019-07-06 15:40 UTC, vangjeannette approved these changes

2019-07-06 19:05 UTC, sblondeau requested changes

2019-07-06 19:05 UTC, sblondeau commented on src/Repository/RolesRepository.php
> +    {
code commenté

2019-07-06 19:05 UTC, sblondeau commented on src/Controller/ClubController.php
> +        if (!isset($members['president'])) {
non ! tu te compliques. Renvoie uniquement members à ton twig et du coup tu n'as pas besoin de ces 3 if
eventuellement c'est dans ton service que tu pourrais t'assurer que tu renvoies bien les 3 types (president, office et member)

2019-07-06 19:05 UTC, sblondeau commented on templates/club/index.html.twig
> +                {% for president in presidents %}
tu répètes 3 fois quasiment le meme code.
Il faudrait plutot que tu boucles sur members, quite à faire une condition pour la correspondance entre le titre en clé du tableau et la traduction "française" comme pour office / membre du bureau

```
{% set fullTitle = %}
{% for member in title, members %}
<div>...
   <p class="card-text">
   {% if title='office' %}Membre du bureau{%elseif title='president'%}Président{%else}...
  </p> 

```

2019-07-08 12:11 UTC, vangjeannette approved these changes

2019-07-08 13:29 UTC, sblondeau requested changes

2019-07-08 13:29 UTC, sblondeau commented on src/Entity/Roles.php
> +class Roles
on est d'accord qu'on ne s'en sert pas finalemement ? à virer.

2019-07-08 13:29 UTC, sblondeau commented on src/Entity/User.php
> +    private $role;
relation manytoone à virer

2019-07-08 13:39 UTC, lamoureux-sylvain approved these changes

2019-07-08 13:43 UTC, sblondeau approved these changes

2019-07-08 13:43 UTC, merged