ajout du userReposository dans les controller modifiés car présence d…
WildCodeSchool/orleans-0219-php-gtb pull request #170
Opened 2019-07-08 15:35 UTC by vangjeannette

…e navbar qui fait appelle à ce repo

2019-07-08 15:46 UTC, MaistrePedro approved these changes

2019-07-08 16:09 UTC, sblondeau requested changes

2019-07-08 16:09 UTC, sblondeau commented on src/Controller/TrombinoscopeController.php
> +            'user' => $userRepository->findOneBy([])
pourquoi tu me fais des findOneBy de Users partout ? ça te fait récup le 1er user de ta table user. Sans doute pas ce que tu cherches à faire ?

2019-07-09 08:00 UTC, laheravilla approved these changes

2019-07-09 08:24 UTC, sblondeau approved these changes

2019-07-09 08:24 UTC, merged