Section Partenaires
WildCodeSchool/orleans-0219-php-gtb pull request #18
Opened 2019-06-05 09:44 UTC by laheravilla

2019-06-05 09:48 UTC, vangjeannette approved these changes

2019-06-05 13:19 UTC, sblondeau requested changes
la partie partenaire doit etre dynamique car administrable

2019-06-05 13:19 UTC, sblondeau commented on assets/scss/app.scss
> +      font-size: 4vw;
encore une fois, je pense que ton truc de medium/small n'est pas adapté :/
regarde plutot https://css-tricks.com/snippets/css/fluid-typography/

2019-06-05 14:59 UTC, laheravilla commented on assets/scss/app.scss
> +      font-size: 4vw;
Done

2019-06-05 15:22 UTC, vangjeannette approved these changes

2019-06-05 15:23 UTC, vangjeannette approved these changes

2019-06-05 15:37 UTC, vangjeannette approved these changes

2019-06-06 09:06 UTC, vangjeannette approved these changes

2019-06-06 13:26 UTC, sblondeau requested changes
27 fichiers...
tu as généré tous les crud, pour 2 types d'entités.
Ca ne va pas, je pense qu'il fallait seulement créer une Entity Partner (donc 2 fichiers), pas plus

2019-06-07 08:47 UTC, vangjeannette approved these changes

2019-06-07 10:14 UTC, sblondeau requested changes

2019-06-07 10:14 UTC, sblondeau commented on src/Repository/SponsorRepository.php
> +    // /**
enlève le code commenté (meme s'il est autogénéré)

2019-06-07 10:14 UTC, sblondeau commented on src/Controller/HomeController.php
>              'controller_name' => 'HomeController',
enlève le controller_name, c'est une variable "exemple" généré par le make:controller. Il ne faut pas la garder

2019-06-07 10:22 UTC, laheravilla commented on src/Controller/HomeController.php
>              'controller_name' => 'HomeController',
Done

2019-06-07 10:27 UTC, vangjeannette approved these changes

2019-06-07 11:07 UTC, laheravilla commented on src/Repository/SponsorRepository.php
> +    // /**
Done

2019-06-07 11:29 UTC, vangjeannette approved these changes

2019-06-07 11:29 UTC, merged