Sprint01 us07 accueil trail
WildCodeSchool/orleans-0219-php-gtb pull request #26
Opened 2019-06-06 09:11 UTC by MaistrePedro

2019-06-06 14:13 UTC, vangjeannette requested changes
Mettre le code html dans un fichier _trail.html.twig et l'inclure dans le fichier template/home/index.html.twig s'il te plait :)

2019-06-06 14:19 UTC, vangjeannette approved these changes

2019-06-07 07:38 UTC, sblondeau requested changes
Image à resizer !!!! j'ai des images à presque 7Mo quand meme :/

2019-06-07 07:38 UTC, sblondeau commented on src/Repository/ContentRepository.php
> +    // /**
enlever le code commenté (meme si autogénéré)

2019-06-07 07:38 UTC, sblondeau commented on templates/home/_trail.html.twig
> +                    {{ content.subtitle |default(' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in eleifend elit. Aliquam pharetra velit
pas de lorem ipsum "en dur". Normalement ce texte provient de la DB.
je dois donc avoir l'entité créee, et une requete pour récup le bon bout de texte

2019-06-07 07:38 UTC, sblondeau commented on src/Entity/Content.php
> +class Content
on peut en rediscuter, mais on s'est dit qu'on ne faisait pas de table Content non ?

2019-06-07 09:36 UTC, vangjeannette approved these changes

2019-06-07 10:20 UTC, sblondeau requested changes

2019-06-07 10:20 UTC, sblondeau commented on assets/scss/app.scss
> +<<<<<<< HEAD
!?@#[+! 
PO > gateau

2019-06-07 10:20 UTC, sblondeau commented on src/Repository/TrailRepository.php
> +    public function findByExampleField($value)
non ! il faut enlever le code commenté, pas le décommenté, ce sont des exemples non fonctionnels

2019-06-07 10:20 UTC, sblondeau commented on src/Repository/ContentRepository.php
> +    public function findByExampleField($value)
à virer, voir commentaire plus bas

2019-06-07 10:20 UTC, sblondeau commented on src/Entity/Trail.php
> +class Trail
Pour moi, il ne faut ni de table Content, ni de table Trail, mais une entity que vous appelé par exemple ClubInfo ou Club ou Association, bref, qui va contenir une seule ligne avec les champs
- trailContent
- trailHomeContent
- triathlonContent
- triathlonHomeContent
- ClubContent
- clubHomeContent
- autre si j'ai oublié qq chose?

2019-06-07 10:20 UTC, sblondeau commented on src/Entity/Trail.php
> +class Trail
le nombre de page et de section n'est pas adminstrable. Passer par une table Content dédiée se justifierait si c'était le cas, mais ça ne l'est pas.

2019-06-07 10:56 UTC, MaistrePedro commented on src/Entity/Trail.php
> +class Trail
Il me semble que c'est tout, on updatera au besoin plus tard

2019-06-07 11:27 UTC, sblondeau requested changes

2019-06-07 11:27 UTC, sblondeau commented on src/Entity/Association.php
> +    private $triaContent;
triathlonContent / triathlonHome (pas d'abbreviation)

2019-06-07 11:27 UTC, sblondeau commented on templates/home/_trail.html.twig
> +                <a href="#" class="btn btn-primary">En savoir plus</a>
En savoir plus sur le trail (on va essayer de suivre les consignes de l'intervention sur l'accessibilité ;-))

2019-06-10 20:13 UTC, sblondeau approved these changes

2019-06-10 20:13 UTC, merged