Fix_US02_Footer
WildCodeSchool/orleans-0219-php-gtb pull request #29
Opened 2019-06-06 11:55 UTC by vangjeannette

Fix pour rééquilibrer les espaces entre les éléments !

2019-06-06 14:04 UTC, lamoureux-sylvain approved these changes

2019-06-06 14:06 UTC, lamoureux-sylvain approved these changes

2019-06-07 07:40 UTC, sblondeau requested changes

2019-06-07 07:40 UTC, sblondeau commented on templates/_footer.html.twig
> +        <div class="address-bis">
balise address

2019-06-07 07:40 UTC, sblondeau commented on templates/_footer.html.twig
> +            <div class="col-12 text-center">
ça ne serait pas mieux avec une icone adaptée fontawesome devant l'adress / tel / mail ?

2019-06-07 09:10 UTC, lamoureux-sylvain approved these changes

2019-06-07 09:20 UTC, laheravilla approved these changes

2019-06-07 10:21 UTC, sblondeau approved these changes

2019-06-07 10:21 UTC, merged