Sprint01_US62_Accueil_LeClub
WildCodeSchool/orleans-0219-php-gtb pull request #34
Opened 2019-06-06 15:16 UTC by vangjeannette

Création de la section "le club" sur la page Accueil 
ATTENTION  SECTION EN DUR DONC NON ADMINISTRABLE !!!!!!!!

2019-06-06 15:18 UTC, lamoureux-sylvain approved these changes

2019-06-07 07:47 UTC, sblondeau requested changes
je ne comprends pas, on a dit que la page était administrable non ? donc pourquoi "en dur" ?

2019-06-07 07:50 UTC, vangjeannette commented
La page est administrable mais juste cette section de la page n'est pas administrable d'où le lorem ipsum en dur

2019-06-07 08:06 UTC, sblondeau approved these changes

2019-06-07 08:06 UTC, merged