Sprint02 us08 accueil section triathlon
WildCodeSchool/orleans-0219-php-gtb pull request #52
Opened 2019-06-12 13:27 UTC by MaistrePedro

2019-06-12 13:51 UTC, laheravilla approved these changes

2019-06-12 13:58 UTC, sblondeau requested changes

2019-06-12 13:58 UTC, sblondeau commented on assets/scss/app.scss
> +#trail {
pas d'id dans le CSS

2019-06-12 13:58 UTC, sblondeau commented on assets/scss/app.scss
> +    z-index: -1000;
pourquoi un z-index négatif ? pourquoi pas -256842456 ?

2019-06-12 13:58 UTC, sblondeau commented on assets/scss/app.scss
> +#triathlon {
meme code CSS que trail, à refacto (et pas d'id dans le CSS)

2019-06-12 13:58 UTC, sblondeau commented on src/Controller/HomeController.php
> +            'association' => $association->findAll(),
findOneBy

2019-06-12 13:58 UTC, sblondeau commented on templates/home/_triathlon.html.twig
> +                {% for ass in association %}
pas d'abbréviation...

2019-06-12 13:58 UTC, sblondeau commented on templates/home/_triathlon.html.twig
> +                {% for ass in association %}
mais pas besoin de tableau avec le findOneBy

2019-06-12 14:04 UTC, lamoureux-sylvain commented on assets/scss/app.scss
> +    z-index: -1000;
huuuum parce que ?

2019-06-12 14:50 UTC, laheravilla approved these changes

2019-06-13 14:15 UTC, sblondeau approved these changes

2019-06-13 14:15 UTC, merged