Sprint02 us63 page login
WildCodeSchool/orleans-0219-php-gtb pull request #53
Opened 2019-06-12 13:44 UTC by vangjeannette

2019-06-12 17:53 UTC, laheravilla approved these changes

2019-06-13 15:03 UTC, sblondeau requested changes

2019-06-13 15:03 UTC, sblondeau commented on assets/scss/app.scss
> +  color: $fond-color;
le nom des variables en anglais, meme pour le css

2019-06-13 15:03 UTC, sblondeau commented on templates/_navbar.html.twig
> +                    <a class="nav-link text-center" href="{{ path('app_logout') }}">DECONNEXION</a>
Ce n'est pas prévu d'ajouter le nom de la personne actuellement connecté ?
sinon ça serait peut être sympa d'ajouter des icones fontawesome devant deconnexion et connexion

2019-06-14 07:34 UTC, vangjeannette commented on templates/_navbar.html.twig
> +                    <a class="nav-link text-center" href="{{ path('app_logout') }}">DECONNEXION</a>
Normalement quand le membre se connectera, le fontawesome sera remplacé car la photo de la personne :)

2019-06-14 07:35 UTC, vangjeannette commented on assets/scss/app.scss
> +  color: $fond-color;
c'était une erreur de frappe fond n'est pas le background mais le font de la police j'ai rectifié :)

2019-06-14 07:46 UTC, laheravilla approved these changes

2019-06-14 08:30 UTC, sblondeau approved these changes

2019-06-14 08:31 UTC, merged