Us10 admin tableau bord - Backend
WildCodeSchool/orleans-0219-php-gtb pull request #80
Opened 2019-06-19 15:04 UTC by laheravilla

2019-06-19 15:19 UTC, vangjeannette approved these changes

2019-06-19 20:13 UTC, sblondeau requested changes

2019-06-19 20:13 UTC, sblondeau commented on src/Entity/User.php
> +    private $comment;
à modifier en $comments ici également, tu as PLUSIEURS comments par USER
(donc modifier les getter/setter/construct en conséquence)

2019-06-19 20:13 UTC, sblondeau commented on src/Repository/EventRepository.php
> +    public function getEventsLessCommented()
je trouve que ces deux méthodes sont un peu répétitives (pas très DRY car tu as juste la direction du tri qui change).
ça serait plus propre d'avoir une seule fonction getEventCommentNumber(string $direction='ASC')

2019-06-19 20:13 UTC, sblondeau commented on templates/admin/index.html.twig
> +                <div class="card m-2">
ici ce n'est pas DRY non plus, tu répète exactement le meme code saut que tu as un eventLessCommented au lieu d'un eventMoreCommented.
Tu peux garder tes blocs mais dedans faire un include et dans le fichier include tu n'aurais que le HTML de la card

2019-06-20 07:35 UTC, laheravilla reviewed
Done

2019-06-20 07:35 UTC, laheravilla commented on src/Entity/User.php
> +    private $comment;
done

2019-06-20 07:35 UTC, laheravilla commented on src/Repository/EventRepository.php
> +    public function getEventsLessCommented()
done

2019-06-20 12:02 UTC, MaistrePedro approved these changes

2019-06-20 13:51 UTC, sblondeau approved these changes

2019-06-20 13:52 UTC, merged