Sprint01 us05 accueil formulaire
WildCodeSchool/orleans-0219-php-gtb pull request #89
Opened 2019-06-25 09:02 UTC by lamoureux-sylvain

https://drive.google.com/open?id=1ePwqyzZBkk8a3Z9MQZlTPziT9DCGpuDaJLfT78M2eYU

2019-06-25 09:03 UTC, lamoureux-sylvain commented
l'envoie sur boite mail en fonction du sujet dans une autre us
sinon tout est là

2019-06-25 09:51 UTC, vangjeannette approved these changes

2019-06-25 10:35 UTC, sblondeau requested changes

2019-06-25 10:35 UTC, sblondeau commented on src/Controller/ContactController.php
> +                array('contact' => $contact)
[] plutot que array()

2019-06-25 10:35 UTC, sblondeau commented on src/Entity/Contact.php
> +     * @Assert\NotBlank(message="Veuillez saisir une adresse email valide.")
si je chipote, le message pour le NotBlank devrait plutot etre "L'email est obligatoire" ou qq chose comme ça

2019-06-25 10:35 UTC, sblondeau commented on templates/contact/email.html.twig
> +    Une nouvelle demande d'information vient de vous être envoyée.
ce template n'étend aucun autre ?
si c'est le cas, il ne faut pas de block body mais partie d'un doctype html (page html "entière")
mais le mieux serait d'étendre un emailLayout qui se chargerait de la structre html de base, et qui pourrait être réutilisé si tu as d'autres mail après à envoyer (à destination des membres par ex)

2019-06-25 10:35 UTC, sblondeau commented on src/Entity/Contact.php
> +    private $subject;
ton subject n'étant pas "libre", il faudrait un assert qui vérifie que tu as bien une des propositions possibles dans le ChoiceType. Dans ce cas, une constante (dans l'entité) reprenant les X choix possibles serait le mieux car réutilisable à plusieurs endroits.
et ça te resservira aussi quand tu auras à faire le choix du mail en fonction du subject !

2019-07-01 13:51 UTC, vangjeannette approved these changes

2019-07-01 14:11 UTC, sblondeau approved these changes

2019-07-01 14:11 UTC, merged