Admin ajout sponsors vich
WildCodeSchool/orleans-0219-php-gtb pull request #91
Opened 2019-06-25 15:14 UTC by laheravilla

2019-06-25 15:31 UTC, lamoureux-sylvain approved these changes

2019-06-25 15:46 UTC, sblondeau requested changes

2019-06-25 15:46 UTC, sblondeau commented on src/Entity/Sponsor.php
> +     * )
il faut rajouter un @Assert\File MaxSize pour lui dire que le max est 1024 si c'est ce que tu veux mettre
la propriété imageSize de ta classe sert elle à enregistrer le poids de l'image uploadée (donc pas vraiment utile dans ton cas).
Si tu voulais un truc vraiment propre, il faudrait par ailleurs mettre ce poids max (et les mimeTypes autorisés) dans des constantes, que tu pourrais ensuite réutiliser dans ton indication dans le form

2019-06-25 15:46 UTC, sblondeau commented on templates/admin/page_home.html.twig
> +                    <small class="text-muted d-block pl-2"><i>*Poids maximum 1024 kilobytes</i></small>
ici j'utiliserai les constantes que tu devrais créer
et par ailleurs plutôt qu'une balise `small`, tu as un form_help qui te permet d'afficher un message (à config dans le formType et c'est là que tu récupérerais les infos de ta constantes)
C'est plus complexe mais beaucoup plus propre car évite les incohérences entre ce qui est attendu et les messages qui s'affichent. Julien l'a fait sur le projet Enedis si tu veux avoir des infos ;-)

2019-06-26 08:59 UTC, laheravilla commented on src/Entity/Sponsor.php
> +     * )
done

2019-06-26 08:59 UTC, laheravilla commented on templates/admin/page_home.html.twig
> +                    <small class="text-muted d-block pl-2"><i>*Poids maximum 1024 kilobytes</i></small>
done

2019-06-26 09:04 UTC, lamoureux-sylvain approved these changes

2019-06-26 10:24 UTC, merged