Sprint03 us37 admin asso
WildCodeSchool/orleans-0219-php-gtb pull request #98
Opened 2019-06-26 09:46 UTC by MaistrePedro

SUMMERNOTE FONCTIONNE KBRQEFKPHBAERFDGHKBDAQSBVHFRAEGF

2019-06-26 10:02 UTC, lamoureux-sylvain approved these changes

2019-06-26 10:26 UTC, sblondeau requested changes

2019-06-26 10:26 UTC, sblondeau commented on templates/association/_form.html.twig
> +{#        {{ form_label(form.clubHome, 'Résumé du Club') }}#}
code commenté !

2019-06-26 10:26 UTC, sblondeau commented on templates/base.html.twig
> +        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
bah non... si tu t'embête à tout charger via webpack, c'est justement pour ne pas charger tes assets via des CDN...

2019-06-26 10:35 UTC, MaistrePedro commented on templates/base.html.twig
> +        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
Même si ce sont d'anciennes versions ?

2019-06-27 14:10 UTC, lamoureux-sylvain approved these changes

2019-07-01 07:01 UTC, sblondeau requested changes

2019-07-01 07:01 UTC, sblondeau commented on assets/js/app.js
> +console.log($('.summernote'));
enlever le console.log (equivalent d'un var_dump en js)

2019-07-01 07:01 UTC, sblondeau commented on templates/association/edit.html.twig
> +    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>
tjs ton problème de chargement d'assets

2019-07-01 10:10 UTC, sblondeau requested changes

2019-07-01 10:10 UTC, sblondeau commented on templates/base.html.twig
>          <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
mais du coup le fontwesome 2 lignes au dessus et le jquery 3-4.1 devraient etre appelés via webpack ! on ne se comprend pas je crois :p 
je t'autorise le jquery 3.2.1 si vraiment tu en as besoin, dans le edit.html.twig, mais sinon je ne dois pas avoir d'appel de js/css à d'autres endroit en "direct".

2019-07-01 10:10 UTC, sblondeau commented on templates/association/edit.html.twig
> +    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
ok s'il te le faut mais le JS dois etre appele dans le block javascripts en bas de page et pas le bloc stylesheets!

2019-07-01 14:25 UTC, vangjeannette approved these changes

2019-07-01 14:45 UTC, sblondeau approved these changes

2019-07-01 14:45 UTC, merged