création d'un nouveau membre
WildCodeSchool/orleans-0219-php-gtb pull request #99
Opened 2019-07-01 08:42 UTC by vangjeannette

2019-07-01 09:00 UTC, lamoureux-sylvain approved these changes

2019-07-01 09:57 UTC, sblondeau requested changes

2019-07-01 09:57 UTC, sblondeau commented on src/Entity/User.php
> +    private $firstname;
manque toutes les validation  @Assert sur l'entity

2019-07-01 09:57 UTC, sblondeau commented on src/Repository/ActivityRepository.php
> +    // /**
code commenté

2019-07-01 09:57 UTC, sblondeau commented on src/Repository/GenderRepository.php
> +    public function findByExampleField($value)
code commenté

2019-07-01 13:52 UTC, lamoureux-sylvain approved these changes

2019-07-01 14:20 UTC, sblondeau requested changes

2019-07-01 14:20 UTC, sblondeau commented on src/Entity/Activity.php
> +    private $activities;
au singulier, si ça t'embête de l'appeler comme le nom de l'entity, tu peux appeler le champ "name" tout simplement, tu ferais ainsi un $activity->getName() plutot qu'un activity->getActivity() qui est plus ambigue

2019-07-01 14:20 UTC, sblondeau commented on src/Entity/Activity.php
> +    public function getActivities(): ?string
getter et setter à renommés du coup

2019-07-01 14:20 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Length(min="8", message="votre mot de passe doit comporter au minimum 8 caractères !")
attention tu l'a mis sur le firstname alors que ça concerne le mot de passe !

2019-07-01 14:20 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Length(max="255", message="votre adresse ne doit pas dépasser 255 caractères !")
remarque valable pour tous tes messages d'erreur, utilise plutot {limit} dans tes messages d'erreur, ça reprend automatiquement la valeur limite que tu as défini (ici dans le max mais ça marche pareil pour des min ou autre).
Comme ça si tu changes la valeur max, tu n'as pas à modifier également le message et ça évite les erreurs

2019-07-01 14:20 UTC, sblondeau commented on templates/security/login.html.twig
> +                    Si vous n'avez pas encore de compte, veuillez cliquer <a href="{{ path('creation_utilisateur') }}">ici</a> , en cas de mot de passe oublié, cliquez <a href="#">ici</a>.
en terme d'accessibilité, un lecteur d'écran lirait "ici" et "ici"
il faudrait mieux faire, plus simplement, 2 liens :  
<a href="{{ path('creation_utilisateur') }}">Créer un compte</a> - <a href="#">mot de passe oublié</a>

2019-07-02 08:54 UTC, lamoureux-sylvain approved these changes

2019-07-02 14:46 UTC, MaistrePedro approved these changes

2019-07-02 21:21 UTC, sblondeau requested changes

2019-07-02 21:21 UTC, sblondeau commented on src/Entity/Gender.php
> +    private $gender_name;
$genderName

et pendant que tu y es, penses à créer les asserts pour Activities et Gender (à moins que ça ne soit prévu pour une autre US?)

2019-07-02 21:21 UTC, sblondeau commented on src/Entity/User.php
> +     *     maxMessage="l'email doit composer {limit} caractères")
doit comporter

2019-07-02 21:21 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Length(min="2", max="255", minMessage="votre mot de passe doit comporter au minimum {limit} caractères" ,
là également, tu es sur firstname et le message parle des password.
Fais également attention à la cohérence, des fois c'est "le mot de passe", après c'est "votre mot de passe"
une fois c'est "doit comporter xx caractères" et la fois d'après "doit comporter au maximum xx caractères"

2019-07-02 21:21 UTC, sblondeau commented on src/Form/UserType.php
> +                'choice_label' => 'gender_name',
ça sera genderName après renommage de la propriété

2019-07-02 21:21 UTC, sblondeau commented on templates/security/login.html.twig
> +                    Si vous n'avez pas encore de compte, veuillez cliquer <a href="{{ path('creation_utilisateur') }}">ici</a> , en cas de mot de passe oublié, cliquez <a href="#">ici</a>.
à modifier

2019-07-03 08:32 UTC, MaistrePedro approved these changes

2019-07-03 08:40 UTC, merged